# This is a GitHub workflow that gets code owners
name: Get Code Owners

# Controls when the action will run. 
on: [pull_request]

env:
  PR_API_URL: ${{ github.event.pull_request.url }}

jobs:
  # This workflow contains a single job
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Check codeowners reviews
        run: |
          REQUESTED_REVIEWERS=$(curl ${{ env.PR_API_URL }}/requested_reviewers --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}')
          echo "requested reviewers: |${REQUESTED_REVIEWERS}|"
